name: Docker Build and Publish

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/**
      - Dockerfile.template
      - Taskfile.yml

jobs:
  build_push:
    name: Build and Push
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install go-task
        uses: Arduino/actions/setup-taskfile@master
        with:
          version: "2.8.0"
      - name: Build
        run: task build
      - name: Push
        run: task push
        env:
          DOCKER_USERNAME : ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD : ${{ secrets.DOCKER_PASSWORD }}
